domain: felixleitner.com

plugins:
  - jekyll-pug

collections_dir: collections

collections:
  skills:
    output: false
  projects:
    output: true
    permalink: /project/:slug
    layout: project
